version: '3'

services:
  taskinity-email:
    image: python:3.9-slim
    container_name: taskinity-email-processor
    volumes:
      - ../../..:/app
      - ./logs:/app/example_email/logs
    working_dir: /app/example_email
    environment:
      - SMTP_SERVER=mailhog
      - SMTP_PORT=1025  # MailHog SMTP port
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - FROM_EMAIL=user@example.com
      - REPLY_TO_EMAIL=support@example.com
      - PYTHONPATH=/app
      - MOCK_EMAILS=true
      - CONTINUOUS_MODE=true
      - KEEP_RUNNING=true
      - LOG_LEVEL=INFO
    command: >
      bash -c "mkdir -p logs && \
               pip install -r requirements.txt && \
               pip install -e /app/python && \
               export PYTHONPATH=/app/python:$PYTHONPATH && \
               cd /app/example_email && \
               python -c 'import sys; print(\"Python path:\", sys.path)' && \
               python flow.py --mock"
    depends_on:
      - mailhog
    networks:
      - taskinity-network
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - taskinity-network
    restart: unless-stopped

networks:
  taskinity-network:
    driver: bridge
